### ISSUE TITLE
firebase_auth is incompatible with flutter_localizations

### ISSUE THREAD

**Issue by siew24** [XMUMY/XMUX#1]
Currently on Flutter 1.27.0-2.0.pre.96 (master channel) and using VS Code with Flutter + Dart extension.

Steps to reproduce: run `flutter pub get` on the current master branch (556044b3a05375549413971e73ddbe087d65677e)

**Comment by ctrysbita** [comment]
Maybe you should try lower version of flutter. We haven't migrated to null-safety yet.

**Comment by siew24** [comment]
That's an option, but I've found a workaround to the issue, downgrading firebase_auth and then running `flutter pub upgrade` resolves the issue. Does that affect anything since I'm still upgrading them?

**Comment by siew24** [comment]
Moving to Flutter stable solves the issue. I'll close this issue
